steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/jab-ai-chatbot-repo/jab-ai-chatbot-service:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/jab-ai-chatbot-repo/jab-ai-chatbot-service:$COMMIT_SHA']

  # Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jab-ai-chatbot-service'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/jab-ai-chatbot-repo/jab-ai-chatbot-service:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/jab-ai-chatbot-repo/jab-ai-chatbot-service:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING
